-- MySQL Script generated by MySQL Workbench
-- Sun Feb 18 16:31:42 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema cancat_proyecto_animal
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cancat_proyecto_animal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cancat_proyecto_animal` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `cancat_proyecto_animal` ;

-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`species` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `image` VARCHAR(255) NULL DEFAULT 'defalut.jpeg',
  `roleId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password` (`password` ASC) VISIBLE,
  INDEX `roleId` (`roleId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`roleId`)
    REFERENCES `cancat_proyecto_animal`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `specieId` INT NOT NULL,
  `userId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `specieId` (`specieId` ASC) VISIBLE,
  INDEX `userId` (`userId` ASC) VISIBLE,
  CONSTRAINT `pets_ibfk_1`
    FOREIGN KEY (`specieId`)
    REFERENCES `cancat_proyecto_animal`.`species` (`id`),
  CONSTRAINT `pets_ibfk_2`
    FOREIGN KEY (`userId`)
    REFERENCES `cancat_proyecto_animal`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paymentMethodsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `paymentMethodsId` (`paymentMethodsId` ASC) VISIBLE,
  CONSTRAINT `tickets_ibfk_1`
    FOREIGN KEY (`paymentMethodsId`)
    REFERENCES `cancat_proyecto_animal`.`payment_methods` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` INT NULL DEFAULT NULL,
  `ticketId` INT NULL DEFAULT NULL,
  `userId` INT NULL DEFAULT NULL,
  `statusId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ticketId` (`ticketId` ASC) VISIBLE,
  INDEX `userId` (`userId` ASC) VISIBLE,
  INDEX `statusId` (`statusId` ASC) VISIBLE,
  CONSTRAINT `sales_ibfk_1`
    FOREIGN KEY (`ticketId`)
    REFERENCES `cancat_proyecto_animal`.`tickets` (`id`),
  CONSTRAINT `sales_ibfk_2`
    FOREIGN KEY (`userId`)
    REFERENCES `cancat_proyecto_animal`.`users` (`id`),
  CONSTRAINT `sales_ibfk_3`
    FOREIGN KEY (`statusId`)
    REFERENCES `cancat_proyecto_animal`.`statuses` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `description` TEXT NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `date_and_time` DATETIME NULL DEFAULT NULL,
  `petId` INT NULL DEFAULT NULL,
  `saleId` INT NULL DEFAULT NULL,
  `serviceId` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `petId` (`petId` ASC) VISIBLE,
  INDEX `saleId` (`saleId` ASC) VISIBLE,
  INDEX `serviceId` (`serviceId` ASC) VISIBLE,
  CONSTRAINT `bookings_ibfk_1`
    FOREIGN KEY (`petId`)
    REFERENCES `cancat_proyecto_animal`.`pets` (`id`),
  CONSTRAINT `bookings_ibfk_2`
    FOREIGN KEY (`saleId`)
    REFERENCES `cancat_proyecto_animal`.`sales` (`id`),
  CONSTRAINT `bookings_ibfk_3`
    FOREIGN KEY (`serviceId`)
    REFERENCES `cancat_proyecto_animal`.`services` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`filings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`filings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `measure` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`flavors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`flavors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `discount` INT NULL DEFAULT NULL,
  `description` TEXT NOT NULL,
  `brandId` INT NOT NULL,
  `specieId` VARCHAR(255) NOT NULL,
  `filingId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `brandId` (`brandId` ASC) VISIBLE,
  INDEX `specieId` (`specieId` ASC) VISIBLE,
  INDEX `filingId` (`filingId` ASC) VISIBLE,
  CONSTRAINT `fk_products_brands`
    FOREIGN KEY (`brandId`)
    REFERENCES `cancat_proyecto_animal`.`brands` (`id`),
  CONSTRAINT `fk_products_species`
    FOREIGN KEY (`specieId`)
    REFERENCES `cancat_proyecto_animal`.`species` (`id`),
  CONSTRAINT `fk_products_filings`
    FOREIGN KEY (`filingId`)
    REFERENCES `cancat_proyecto_animal`.`filings` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`image_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`image_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(255) NOT NULL,
  `productId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `image_products_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `cancat_proyecto_animal`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `productId` INT NOT NULL,
  `saleId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productId` (`productId` ASC) VISIBLE,
  INDEX `saleId` (`saleId` ASC) VISIBLE,
  CONSTRAINT `items_ibfk_1`
    FOREIGN KEY (`productId`)
    REFERENCES `cancat_proyecto_animal`.`products` (`id`),
  CONSTRAINT `items_ibfk_2`
    FOREIGN KEY (`saleId`)
    REFERENCES `cancat_proyecto_animal`.`sales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`sequelizemeta` (
  `name` VARCHAR(255) COLLATE 'utf8mb3_unicode_ci' NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cancat_proyecto_animal`.`stocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cancat_proyecto_animal`.`stocks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flavorId` INT NOT NULL,
  `productId` INT NOT NULL,
  `amount` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `flavorId` (`flavorId` ASC) VISIBLE,
  INDEX `productId` (`productId` ASC) VISIBLE,
  CONSTRAINT `stocks_ibfk_1`
    FOREIGN KEY (`flavorId`)
    REFERENCES `cancat_proyecto_animal`.`flavors` (`id`),
  CONSTRAINT `stocks_ibfk_2`
    FOREIGN KEY (`productId`)
    REFERENCES `cancat_proyecto_animal`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
