-- MySQL Script generated by MySQL Workbench
-- Fri Feb 16 20:31:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CanCat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CanCat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CanCat` DEFAULT CHARACTER SET utf8 ;
USE `CanCat` ;

-- -----------------------------------------------------
-- Table `CanCat`.`flavors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`flavors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`species`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`species` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`filings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`filings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `measure` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT UNSIGNED NOT NULL,
  `discount` INT UNSIGNED NULL,
  `description` TEXT NOT NULL,
  `brandId` INT NULL,
  `specieId` INT NULL,
  `flingId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sabores_productos_idx` (`brandId` ASC) VISIBLE,
  INDEX `fk_categoria_productos_idx` (`specieId` ASC) VISIBLE,
  INDEX `fk_filings_products_idx` (`flingId` ASC) VISIBLE,
  CONSTRAINT `fk_flavors_products`
    FOREIGN KEY (`brandId`)
    REFERENCES `CanCat`.`flavors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_species_products`
    FOREIGN KEY (`specieId`)
    REFERENCES `CanCat`.`species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brands_products`
    FOREIGN KEY (`brandId`)
    REFERENCES `CanCat`.`brands` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filings_products`
    FOREIGN KEY (`flingId`)
    REFERENCES `CanCat`.`filings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(150) NOT NULL,
  `image` VARCHAR(100) NULL DEFAULT 'default.png',
  `roleId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAr` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE,
  INDEX `fk_roles_usuarios_idx` (`roleId` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roleId`)
    REFERENCES `CanCat`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`images_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`images_products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(100) NOT NULL DEFAULT 'default.jpg',
  `productoId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_imagenes_productos_idx` (`productoId` ASC) VISIBLE,
  CONSTRAINT `fk_images_products_products`
    FOREIGN KEY (`productoId`)
    REFERENCES `CanCat`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`pets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`pets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `specieId` INT NOT NULL,
  `userId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_mascota_usuario_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_species_pets_idx` (`specieId` ASC) VISIBLE,
  CONSTRAINT `fk_mascota_usuario`
    FOREIGN KEY (`userId`)
    REFERENCES `CanCat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_species_pets`
    FOREIGN KEY (`specieId`)
    REFERENCES `CanCat`.`species` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`payment_methods`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`payment_methods` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`tickets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `paymentMethodsId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fr_forma_de_pago_factura_idx` (`paymentMethodsId` ASC) VISIBLE,
  CONSTRAINT `fr_forma_de_pago_factura`
    FOREIGN KEY (`paymentMethodsId`)
    REFERENCES `CanCat`.`payment_methods` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`statuses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticketId` INT NULL,
  `userId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  `total` INT NULL,
  `statusId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_venta_usuario_idx` (`userId` ASC) VISIBLE,
  INDEX `fk_venta_factura_idx` (`ticketId` ASC) VISIBLE,
  INDEX `fk_statuses_sales_idx` (`statusId` ASC) VISIBLE,
  CONSTRAINT `fk_sales_users`
    FOREIGN KEY (`userId`)
    REFERENCES `CanCat`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_tickts`
    FOREIGN KEY (`ticketId`)
    REFERENCES `CanCat`.`tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_statuses_sales`
    FOREIGN KEY (`statusId`)
    REFERENCES `CanCat`.`statuses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `descripcion` TEXT NOT NULL,
  `descuento` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`bookings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`bookings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_y_hora_resaerva` DATETIME NULL,
  `petId` INT NULL,
  `sale_id` INT NULL,
  `servicioId` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_reserva_servicio_idx` (`servicioId` ASC) VISIBLE,
  INDEX `fk_bookins_pets_idx` (`petId` ASC) VISIBLE,
  CONSTRAINT `fk_bookings_pets`
    FOREIGN KEY (`petId`)
    REFERENCES `CanCat`.`pets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_sales`
    FOREIGN KEY (`sale_id`)
    REFERENCES `CanCat`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bookings_services`
    FOREIGN KEY (`servicioId`)
    REFERENCES `CanCat`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`stock` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `flavorId` INT NULL,
  `productId` INT NULL,
  `amount` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flavors_products_idx` (`flavorId` ASC) VISIBLE,
  INDEX `fk_products_flavors_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_flavors_products`
    FOREIGN KEY (`flavorId`)
    REFERENCES `CanCat`.`flavors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_flavors`
    FOREIGN KEY (`productId`)
    REFERENCES `CanCat`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CanCat`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CanCat`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NULL,
  `productId` INT NOT NULL,
  `saleId` INT NOT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_factura_producto_idx` (`productId` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_products`
    FOREIGN KEY (`productId`)
    REFERENCES `CanCat`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sales_products`
    FOREIGN KEY (`saleId`)
    REFERENCES `CanCat`.`sales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
